export const timeLineDataList = [
  {
    userName: "facebook",
    actionType: "starred a repository",
    time: "2 hours ago",
    repositoryName: "facebook/react",
    description:
      "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
    language: "JavaScript",
    starCount: "160k",
  },
  {
    userName: "google",
    actionType: "created a repository",
    time: "2 hours ago",
    repositoryName: "google/googletest",
    description: "GoogleTest - Google Testing and Mocking Framework",
    language: "C++",
    starCount: "20.9k",
  },
  {
    userName: "microsoft",
    actionType: "starred a repository",
    time: "2 hours ago",
    repositoryName: "microsoft/vscode",
    description: "Visual Studio Code",
    language: "C",
    starCount: "100k",
  },
  {
    userName: "torvalds",
    actionType: "created a repository",
    time: "2 hours ago",
    repositoryName: "torvalds/linux",
    description: "Linux kernel source tree",
    language: "C",
    starCount: "1000k",
  },
  {
    userName: "apple",
    actionType: "starred a repository",
    time: "2 hours ago",
    repositoryName: "apple/swift",
    description: "The Swift Programming Language",
    language: "Swift",
    starCount: "400k",
  },
  {
    userName: "github",
    actionType: "starred a repository",
    time: "2 hours ago",
    repositoryName: "github/gitignore",
    description: "A collection of useful .gitignore templates",
    language: "Shell",
    starCount: "100k",
  },
  {
    userName: "Deno",
    actionType: "starred a repository",
    time: "2 hours ago",
    repositoryName: "denoland/deno",
    description: "A secure runtime for JavaScript and TypeScript",
    language: "Rust",
    starCount: "100k",
  },
];
